# Generated by Django 5.0.6 on 2024-06-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produit", "0002_tag_produit_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="categorie",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="produit",
            name="quantite_stock",
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
