# Generated by Django 5.0.6 on 2024-06-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produit", "0003_produit_categorie_produit_quantite_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="quantite_stock",
            field=models.IntegerField(null=True),
        ),
    ]
