# Generated by Django 5.0.6 on 2024-06-10 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("client", "0001_initial"),
        ("produit", "0002_tag_produit_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("En instance", "En instance"),
                            ("Non livré", "Non livré"),
                            ("Livré", "Livré"),
                        ],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="client.client",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produit.produit",
                    ),
                ),
            ],
        ),
    ]
