# Generated by Django 5.0.6 on 2024-06-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commande", "0003_alter_commande_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="montant_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
