# Generated by Django 5.0.6 on 2024-06-12 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commande", "0004_alter_commande_montant_total"),
        ("produit", "0004_alter_produit_quantite_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commande",
            name="produits",
        ),
        migrations.AddField(
            model_name="commande",
            name="produit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="produit.produit",
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="quantite",
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name="OrderProduct",
        ),
    ]
