# Generated by Django 5.0.6 on 2024-06-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="addresse",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="dernier_modif",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="client",
            name="prenom",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="societe",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="telephone",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
